title: My profile :D
author: GitHub User
email: kokicangela@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Hi! My name is Angela and I'm a second year student at University of Essex.I study Psychology with Cognitive Neuroscience, but I am very interested in coding and AI, so that's why I started learning about GitHub!
# social links
instagram_username: kb.angela
github_username:  angelakokic

show_excerpts: false
theme: minima
